/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: AlMatrixTopNEntry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row alMatrixTopNEntry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class AlMatrixTopNEntry extends AgentXEntry
{

    protected int alMatrixTopNIndex = 0;
    protected int alMatrixTopNProtocolDirLocalIndex = 0;
    protected byte[] alMatrixTopNSourceAddress = new byte[0];
    protected byte[] alMatrixTopNDestAddress = new byte[0];
    protected int alMatrixTopNAppProtocolDirLocalIndex = 0;
    protected long alMatrixTopNPktRate = 0;
    protected long alMatrixTopNReversePktRate = 0;
    protected long alMatrixTopNOctetRate = 0;
    protected long alMatrixTopNReverseOctetRate = 0;
    // foreign indices
    protected int alMatrixTopNControlIndex;

    public AlMatrixTopNEntry(int alMatrixTopNControlIndex,
                             int alMatrixTopNIndex)
    {
        this.alMatrixTopNControlIndex = alMatrixTopNControlIndex;
        this.alMatrixTopNIndex = alMatrixTopNIndex;

        instance.append(alMatrixTopNControlIndex);
        instance.append(alMatrixTopNIndex);
    }

    public int get_alMatrixTopNControlIndex()
    {
        return alMatrixTopNControlIndex;
    }

    public int get_alMatrixTopNIndex()
    {
        return alMatrixTopNIndex;
    }

    public int get_alMatrixTopNProtocolDirLocalIndex()
    {
        return alMatrixTopNProtocolDirLocalIndex;
    }

    public byte[] get_alMatrixTopNSourceAddress()
    {
        return alMatrixTopNSourceAddress;
    }

    public byte[] get_alMatrixTopNDestAddress()
    {
        return alMatrixTopNDestAddress;
    }

    public int get_alMatrixTopNAppProtocolDirLocalIndex()
    {
        return alMatrixTopNAppProtocolDirLocalIndex;
    }

    public long get_alMatrixTopNPktRate()
    {
        return alMatrixTopNPktRate;
    }

    public long get_alMatrixTopNReversePktRate()
    {
        return alMatrixTopNReversePktRate;
    }

    public long get_alMatrixTopNOctetRate()
    {
        return alMatrixTopNOctetRate;
    }

    public long get_alMatrixTopNReverseOctetRate()
    {
        return alMatrixTopNReverseOctetRate;
    }

}

