/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: Channel2Entry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row channel2Entry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class Channel2Entry extends AgentXEntry
{

    protected long channelDroppedFrames = 0;
    protected long channelCreateTime = 0;

    public Channel2Entry()
    {

    }

    public long get_channelDroppedFrames()
    {
        return channelDroppedFrames;
    }

    public long get_channelCreateTime()
    {
        return channelCreateTime;
    }

}

