/*
 * This Java file has been generated by smidump 0.5.0. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row dot1dBasePortEntry defined in BRIDGE-MIB.

    @version 1
    @author  smidump 0.5.0
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class Dot1dBasePortEntry extends AgentXEntry
{

    protected int dot1dBasePort = 0;
    protected int dot1dBasePortIfIndex = 0;
    protected AgentXOID dot1dBasePortCircuit = new AgentXOID();
    protected long dot1dBasePortDelayExceededDiscards = 0;
    protected long dot1dBasePortMtuExceededDiscards = 0;

    public Dot1dBasePortEntry(int dot1dBasePort)
    {
        this.dot1dBasePort = dot1dBasePort;

        instance.append(dot1dBasePort);
    }

    public int get_dot1dBasePort()
    {
        return dot1dBasePort;
    }

    public int get_dot1dBasePortIfIndex()
    {
        return dot1dBasePortIfIndex;
    }

    public AgentXOID get_dot1dBasePortCircuit()
    {
        return dot1dBasePortCircuit;
    }

    public long get_dot1dBasePortDelayExceededDiscards()
    {
        return dot1dBasePortDelayExceededDiscards;
    }

    public long get_dot1dBasePortMtuExceededDiscards()
    {
        return dot1dBasePortMtuExceededDiscards;
    }

}

