/*
 * This Java file has been generated by smidump 0.5.0. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the scalar group dot1dTp defined in BRIDGE-MIB.
 */

import java.util.Vector;
import java.util.Enumeration;
import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;

public class Dot1dTpImpl extends Dot1dTp
{

    public long get_dot1dTpLearnedEntryDiscards()
    {
        return dot1dTpLearnedEntryDiscards;
    }

    public int get_dot1dTpAgingTime()
    {
        return dot1dTpAgingTime;
    }

    public int set_dot1dTpAgingTime(AgentXSetPhase phase, int value)
    {
        switch (phase.getPhase()) {
        case AgentXSetPhase.TEST_SET:
            break;
        case AgentXSetPhase.COMMIT:
            undo_dot1dTpAgingTime = dot1dTpAgingTime;
            dot1dTpAgingTime = value;
            break;
        case AgentXSetPhase.UNDO:
            dot1dTpAgingTime = undo_dot1dTpAgingTime;
            break;
        case AgentXSetPhase.CLEANUP:
            undo_dot1dTpAgingTime = -1; // TODO: better check!
            break;
        default:
            return AgentXResponsePDU.PROCESSING_ERROR;
        }
        return AgentXResponsePDU.NO_ERROR;
    }

}

