/*
 * This Java file has been generated by smidump 0.5.0. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the scalar group dot1dTp defined in BRIDGE-MIB.

    @version 1
    @author  smidump 0.5.0
    @see     AgentXGroup, AgentXScalars
 */

import java.util.Vector;
import java.util.Enumeration;
import jax.AgentXOID;
import jax.AgentXVarBind;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXScalars;

public class Dot1dTp extends AgentXScalars
{

    private final static long[] Dot1dTpOID = {1, 3, 6, 1, 2, 1, 17, 4};

    protected AgentXOID Dot1dTpLearnedEntryDiscardsOID;
    protected final static long[] Dot1dTpLearnedEntryDiscardsName = {1, 3, 6, 1, 2, 1, 17, 4, 1, 0};
    protected long dot1dTpLearnedEntryDiscards = 0;
    protected AgentXOID Dot1dTpAgingTimeOID;
    protected final static long[] Dot1dTpAgingTimeName = {1, 3, 6, 1, 2, 1, 17, 4, 2, 0};
    protected int dot1dTpAgingTime = 0;
    protected int undo_dot1dTpAgingTime = 0;
    public Dot1dTp()
    {
        oid = new AgentXOID(Dot1dTpOID);
        data = new Vector();
        Dot1dTpLearnedEntryDiscardsOID = new AgentXOID(Dot1dTpLearnedEntryDiscardsName);
        data.addElement(Dot1dTpLearnedEntryDiscardsOID);
        Dot1dTpAgingTimeOID = new AgentXOID(Dot1dTpAgingTimeName);
        data.addElement(Dot1dTpAgingTimeOID);
    }

    public long get_dot1dTpLearnedEntryDiscards()
    {
        return dot1dTpLearnedEntryDiscards;
    }

    public int get_dot1dTpAgingTime()
    {
        return dot1dTpAgingTime;
    }

    public int set_dot1dTpAgingTime(AgentXSetPhase phase, int value)
    {
        switch (phase.getPhase()) {
        case AgentXSetPhase.TEST_SET:
            break;
        case AgentXSetPhase.COMMIT:
            undo_dot1dTpAgingTime = dot1dTpAgingTime;
            dot1dTpAgingTime = value;
            break;
        case AgentXSetPhase.UNDO:
            dot1dTpAgingTime = undo_dot1dTpAgingTime;
            break;
        case AgentXSetPhase.CLEANUP:
            break;
        default:
            return AgentXResponsePDU.PROCESSING_ERROR;
        }
        return AgentXResponsePDU.NO_ERROR;
    }
    public AgentXVarBind getScalar(AgentXOID pos, AgentXOID oid)
    {
        if ((pos == null) || (pos.compareTo(oid) != 0))
            return new AgentXVarBind(oid, AgentXVarBind.NOSUCHOBJECT);
        else {
            if (pos == Dot1dTpLearnedEntryDiscardsOID)
                return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, 
                                         get_dot1dTpLearnedEntryDiscards());
            if (pos == Dot1dTpAgingTimeOID)
                return new AgentXVarBind(oid, AgentXVarBind.INTEGER, 
                                         get_dot1dTpAgingTime());
        }
        return new AgentXVarBind(oid, AgentXVarBind.NOSUCHOBJECT);
    }

    public int setScalar(AgentXSetPhase phase, AgentXOID pos,
                         AgentXVarBind inVb)
    {
        if ((pos == null) || (pos.compareTo(inVb.getOID()) != 0))
            return AgentXResponsePDU.INCONSISTENT_NAME;
        else {
            if (pos == Dot1dTpAgingTimeOID)
                return set_dot1dTpAgingTime(phase, inVb.intValue());
        }
        return AgentXResponsePDU.NOT_WRITABLE;
    }

    public AgentXVarBind getNextScalar(AgentXOID pos, AgentXOID oid)
    {
        if ((pos == null) || (pos.compareTo(oid) <= 0))
            return new AgentXVarBind(oid, AgentXVarBind.ENDOFMIBVIEW);
        else {
            if (pos == Dot1dTpLearnedEntryDiscardsOID)
                return new AgentXVarBind(pos, AgentXVarBind.COUNTER32, 
                                         get_dot1dTpLearnedEntryDiscards());
            if (pos == Dot1dTpAgingTimeOID)
                return new AgentXVarBind(pos, AgentXVarBind.INTEGER, 
                                         get_dot1dTpAgingTime());
        }
        return new AgentXVarBind(pos, AgentXVarBind.ENDOFMIBVIEW);
    }

}

