/*
 * This Java file has been generated by smidump 0.5.0. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the table row dot1dTpFdbEntry defined in BRIDGE-MIB.
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class Dot1dTpFdbEntryImpl extends Dot1dTpFdbEntry
{

    // constructor
    public Dot1dTpFdbEntryImpl(byte[] dot1dTpFdbAddress)
    {
        super(dot1dTpFdbAddress);
    }

    public byte[] get_dot1dTpFdbAddress()
    {
        return dot1dTpFdbAddress;
    }

    public int get_dot1dTpFdbPort()
    {
        return dot1dTpFdbPort;
    }

    public int get_dot1dTpFdbStatus()
    {
        return dot1dTpFdbStatus;
    }

}

