/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: HlMatrixControlTable.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table hlMatrixControlTable defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable
 */

import java.util.Vector;

import jax.AgentXOID;
import jax.AgentXVarBind;
import jax.AgentXResponsePDU;
import jax.AgentXSetPhase;
import jax.AgentXTable;
import jax.AgentXEntry;

public class HlMatrixControlTable extends AgentXTable
{

    // entry OID
    private final static long[] OID = {1, 3, 6, 1, 2, 1, 16, 15, 1, 1};

    // constructors
    public HlMatrixControlTable()
    {
        oid = new AgentXOID(OID);

        // register implemented columns
        columns.addElement(new Long(2));
        columns.addElement(new Long(3));
        columns.addElement(new Long(4));
        columns.addElement(new Long(5));
        columns.addElement(new Long(6));
        columns.addElement(new Long(7));
        columns.addElement(new Long(8));
        columns.addElement(new Long(9));
        columns.addElement(new Long(10));
        columns.addElement(new Long(11));
        columns.addElement(new Long(12));
    }

    public HlMatrixControlTable(boolean shared)
    {
        super(shared);

        oid = new AgentXOID(OID);

        // register implemented columns
        columns.addElement(new Long(2));
        columns.addElement(new Long(3));
        columns.addElement(new Long(4));
        columns.addElement(new Long(5));
        columns.addElement(new Long(6));
        columns.addElement(new Long(7));
        columns.addElement(new Long(8));
        columns.addElement(new Long(9));
        columns.addElement(new Long(10));
        columns.addElement(new Long(11));
        columns.addElement(new Long(12));
    }

    public AgentXVarBind getVarBind(AgentXEntry entry, long column)
    {
        AgentXOID oid = new AgentXOID(getOID(), column, entry.getInstance());

        switch ((int)column) {
        case 2: // hlMatrixControlDataSource
        {
            AgentXOID value = ((HlMatrixControlEntry)entry).get_hlMatrixControlDataSource();
            return new AgentXVarBind(oid, AgentXVarBind.OBJECTIDENTIFIER, value);
        }
        case 3: // hlMatrixControlNlDroppedFrames
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlNlDroppedFrames();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 4: // hlMatrixControlNlInserts
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlNlInserts();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 5: // hlMatrixControlNlDeletes
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlNlDeletes();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 6: // hlMatrixControlNlMaxDesiredEntries
        {
            int value = ((HlMatrixControlEntry)entry).get_hlMatrixControlNlMaxDesiredEntries();
            return new AgentXVarBind(oid, AgentXVarBind.INTEGER, value);
        }
        case 7: // hlMatrixControlAlDroppedFrames
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlAlDroppedFrames();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 8: // hlMatrixControlAlInserts
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlAlInserts();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 9: // hlMatrixControlAlDeletes
        {
            long value = ((HlMatrixControlEntry)entry).get_hlMatrixControlAlDeletes();
            return new AgentXVarBind(oid, AgentXVarBind.COUNTER32, value);
        }
        case 10: // hlMatrixControlAlMaxDesiredEntries
        {
            int value = ((HlMatrixControlEntry)entry).get_hlMatrixControlAlMaxDesiredEntries();
            return new AgentXVarBind(oid, AgentXVarBind.INTEGER, value);
        }
        case 11: // hlMatrixControlOwner
        {
            byte[] value = ((HlMatrixControlEntry)entry).get_hlMatrixControlOwner();
            return new AgentXVarBind(oid, AgentXVarBind.OCTETSTRING, value);
        }
        case 12: // hlMatrixControlStatus
        {
            int value = ((HlMatrixControlEntry)entry).get_hlMatrixControlStatus();
            return new AgentXVarBind(oid, AgentXVarBind.INTEGER, value);
        }
        }

        return null;
    }

    public int setEntry(AgentXSetPhase phase,
                        AgentXEntry entry,
                        long column,
                        AgentXVarBind vb)
    {

        switch ((int)column) {
        case 2: // hlMatrixControlDataSource
        {
            if (vb.getType() != AgentXVarBind.OBJECTIDENTIFIER)
                return AgentXResponsePDU.WRONG_TYPE;
            else
                return ((HlMatrixControlEntry)entry).set_hlMatrixControlDataSource(phase, vb.AgentXOIDValue());
        }
        case 6: // hlMatrixControlNlMaxDesiredEntries
        {
            if (vb.getType() != AgentXVarBind.INTEGER)
                return AgentXResponsePDU.WRONG_TYPE;
            else
                return ((HlMatrixControlEntry)entry).set_hlMatrixControlNlMaxDesiredEntries(phase, vb.intValue());
        }
        case 10: // hlMatrixControlAlMaxDesiredEntries
        {
            if (vb.getType() != AgentXVarBind.INTEGER)
                return AgentXResponsePDU.WRONG_TYPE;
            else
                return ((HlMatrixControlEntry)entry).set_hlMatrixControlAlMaxDesiredEntries(phase, vb.intValue());
        }
        case 11: // hlMatrixControlOwner
        {
            if (vb.getType() != AgentXVarBind.OCTETSTRING)
                return AgentXResponsePDU.WRONG_TYPE;
            else
                return ((HlMatrixControlEntry)entry).set_hlMatrixControlOwner(phase, vb.bytesValue());
        }
        case 12: // hlMatrixControlStatus
        {
            if (vb.getType() != AgentXVarBind.INTEGER)
                return AgentXResponsePDU.WRONG_TYPE;
            else
                return ((HlMatrixControlEntry)entry).set_hlMatrixControlStatus(phase, vb.intValue());
        }
        }

        return AgentXResponsePDU.NOT_WRITABLE;
    }

}

