/*
 * This Java file has been generated by smidump 0.4.5. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id: IfJackEntryImpl.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the table row ifJackEntry defined in MAU-MIB.
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class IfJackEntryImpl extends IfJackEntry
{

    // constructor
    public IfJackEntryImpl(int ifMauIfIndex,
                       int ifMauIndex,
                       int ifJackIndex)
    {
        super(ifMauIfIndex,
             ifMauIndex,
             ifJackIndex);
    }

    public int get_ifJackType()
    {
        return ifJackType;
    }

}

