/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: IfStackEntry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row ifStackEntry defined in IF-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class IfStackEntry extends AgentXEntry
{

    protected int ifStackHigherLayer = 0;
    protected int ifStackLowerLayer = 0;
    protected int ifStackStatus = 0;
    protected int undo_ifStackStatus = 0;

    public IfStackEntry(int ifStackHigherLayer,
                        int ifStackLowerLayer)
    {
        this.ifStackHigherLayer = ifStackHigherLayer;
        this.ifStackLowerLayer = ifStackLowerLayer;

        instance.append(ifStackHigherLayer);
        instance.append(ifStackLowerLayer);
    }

    public int get_ifStackHigherLayer()
    {
        return ifStackHigherLayer;
    }

    public int get_ifStackLowerLayer()
    {
        return ifStackLowerLayer;
    }

    public int get_ifStackStatus()
    {
        return ifStackStatus;
    }

    public int set_ifStackStatus(AgentXSetPhase phase, int value)
    {
        switch (phase.getPhase()) {
        case AgentXSetPhase.TEST_SET:
            break;
        case AgentXSetPhase.COMMIT:
            undo_ifStackStatus = ifStackStatus;
            ifStackStatus = value;
            break;
        case AgentXSetPhase.UNDO:
            ifStackStatus = undo_ifStackStatus;
            break;
        case AgentXSetPhase.CLEANUP:
            break;
        default:
            return AgentXResponsePDU.PROCESSING_ERROR;
        }
        return AgentXResponsePDU.NO_ERROR;
    }
}

