/*
 * This Java file has been generated by smidump 0.4.5. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id: MatrixControl2EntryImpl.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the table row matrixControl2Entry defined in RMON2-MIB.
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class MatrixControl2EntryImpl extends MatrixControl2Entry
{

    // constructor
    public MatrixControl2EntryImpl()
    {
        super();
    }

    public long get_matrixControlDroppedFrames()
    {
        return matrixControlDroppedFrames;
    }

    public long get_matrixControlCreateTime()
    {
        return matrixControlCreateTime;
    }

}

