/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: NlMatrixTopNEntry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row nlMatrixTopNEntry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class NlMatrixTopNEntry extends AgentXEntry
{

    protected int nlMatrixTopNIndex = 0;
    protected int nlMatrixTopNProtocolDirLocalIndex = 0;
    protected byte[] nlMatrixTopNSourceAddress = new byte[0];
    protected byte[] nlMatrixTopNDestAddress = new byte[0];
    protected long nlMatrixTopNPktRate = 0;
    protected long nlMatrixTopNReversePktRate = 0;
    protected long nlMatrixTopNOctetRate = 0;
    protected long nlMatrixTopNReverseOctetRate = 0;
    // foreign indices
    protected int nlMatrixTopNControlIndex;

    public NlMatrixTopNEntry(int nlMatrixTopNControlIndex,
                             int nlMatrixTopNIndex)
    {
        this.nlMatrixTopNControlIndex = nlMatrixTopNControlIndex;
        this.nlMatrixTopNIndex = nlMatrixTopNIndex;

        instance.append(nlMatrixTopNControlIndex);
        instance.append(nlMatrixTopNIndex);
    }

    public int get_nlMatrixTopNControlIndex()
    {
        return nlMatrixTopNControlIndex;
    }

    public int get_nlMatrixTopNIndex()
    {
        return nlMatrixTopNIndex;
    }

    public int get_nlMatrixTopNProtocolDirLocalIndex()
    {
        return nlMatrixTopNProtocolDirLocalIndex;
    }

    public byte[] get_nlMatrixTopNSourceAddress()
    {
        return nlMatrixTopNSourceAddress;
    }

    public byte[] get_nlMatrixTopNDestAddress()
    {
        return nlMatrixTopNDestAddress;
    }

    public long get_nlMatrixTopNPktRate()
    {
        return nlMatrixTopNPktRate;
    }

    public long get_nlMatrixTopNReversePktRate()
    {
        return nlMatrixTopNReversePktRate;
    }

    public long get_nlMatrixTopNOctetRate()
    {
        return nlMatrixTopNOctetRate;
    }

    public long get_nlMatrixTopNReverseOctetRate()
    {
        return nlMatrixTopNReverseOctetRate;
    }

}

