/*
 * This Java file has been generated by smidump 0.4.5. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id: NlMatrixDSEntryImpl.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the table row nlMatrixDSEntry defined in RMON2-MIB.
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class NlMatrixDSEntryImpl extends NlMatrixDSEntry
{

    // constructor
    public NlMatrixDSEntryImpl(int hlMatrixControlIndex,
                           long nlMatrixDSTimeMark,
                           int protocolDirLocalIndex,
                           byte[] nlMatrixDSDestAddress,
                           byte[] nlMatrixDSSourceAddress)
    {
        super(hlMatrixControlIndex,
                 nlMatrixDSTimeMark,
                 protocolDirLocalIndex,
                 nlMatrixDSDestAddress,
                 nlMatrixDSSourceAddress);
    }

    public long get_nlMatrixDSPkts()
    {
        return nlMatrixDSPkts;
    }

    public long get_nlMatrixDSOctets()
    {
        return nlMatrixDSOctets;
    }

    public long get_nlMatrixDSCreateTime()
    {
        return nlMatrixDSCreateTime;
    }

}

