/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: NlMatrixSDEntry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row nlMatrixSDEntry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class NlMatrixSDEntry extends AgentXEntry
{

    protected long nlMatrixSDTimeMark = 0;
    protected byte[] nlMatrixSDSourceAddress = new byte[0];
    protected byte[] nlMatrixSDDestAddress = new byte[0];
    protected long nlMatrixSDPkts = 0;
    protected long nlMatrixSDOctets = 0;
    protected long nlMatrixSDCreateTime = 0;
    // foreign indices
    protected int hlMatrixControlIndex;
    protected int protocolDirLocalIndex;

    public NlMatrixSDEntry(int hlMatrixControlIndex,
                           long nlMatrixSDTimeMark,
                           int protocolDirLocalIndex,
                           byte[] nlMatrixSDSourceAddress,
                           byte[] nlMatrixSDDestAddress)
    {
        this.hlMatrixControlIndex = hlMatrixControlIndex;
        this.nlMatrixSDTimeMark = nlMatrixSDTimeMark;
        this.protocolDirLocalIndex = protocolDirLocalIndex;
        this.nlMatrixSDSourceAddress = nlMatrixSDSourceAddress;
        this.nlMatrixSDDestAddress = nlMatrixSDDestAddress;

        instance.append(hlMatrixControlIndex);
        instance.append(nlMatrixSDTimeMark);
        instance.append(protocolDirLocalIndex);
        instance.append(nlMatrixSDSourceAddress);
        instance.append(nlMatrixSDDestAddress);
    }

    public int get_hlMatrixControlIndex()
    {
        return hlMatrixControlIndex;
    }

    public long get_nlMatrixSDTimeMark()
    {
        return nlMatrixSDTimeMark;
    }

    public int get_protocolDirLocalIndex()
    {
        return protocolDirLocalIndex;
    }

    public byte[] get_nlMatrixSDSourceAddress()
    {
        return nlMatrixSDSourceAddress;
    }

    public byte[] get_nlMatrixSDDestAddress()
    {
        return nlMatrixSDDestAddress;
    }

    public long get_nlMatrixSDPkts()
    {
        return nlMatrixSDPkts;
    }

    public long get_nlMatrixSDOctets()
    {
        return nlMatrixSDOctets;
    }

    public long get_nlMatrixSDCreateTime()
    {
        return nlMatrixSDCreateTime;
    }

}

