/*
 * This Java file has been generated by smidump 0.4.5. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: ProtocolDistStatsEntry.java 4432 2006-05-29 16:21:11Z strauss $
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row protocolDistStatsEntry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.4.5
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class ProtocolDistStatsEntry extends AgentXEntry
{

    protected long protocolDistStatsPkts = 0;
    protected long protocolDistStatsOctets = 0;
    // foreign indices
    protected int protocolDistControlIndex;
    protected int protocolDirLocalIndex;

    public ProtocolDistStatsEntry(int protocolDistControlIndex,
                                  int protocolDirLocalIndex)
    {
        this.protocolDistControlIndex = protocolDistControlIndex;
        this.protocolDirLocalIndex = protocolDirLocalIndex;

        instance.append(protocolDistControlIndex);
        instance.append(protocolDirLocalIndex);
    }

    public int get_protocolDistControlIndex()
    {
        return protocolDistControlIndex;
    }

    public int get_protocolDirLocalIndex()
    {
        return protocolDirLocalIndex;
    }

    public long get_protocolDistStatsPkts()
    {
        return protocolDistStatsPkts;
    }

    public long get_protocolDistStatsOctets()
    {
        return protocolDistStatsOctets;
    }

}

