qwt_math.h
NAME
qwt_math.h -
Detailed Description
A set of mathematical routines.
Definition in file qwt_math.h.
SYNOPSIS
Defines
#define qwtMax qMax
#define qwtMin qMin
#define qwtAbs qAbs
#define LOG10_2 0.30102999566398119802
#define LOG10_3 0.47712125471966243540
#define LOG10_5 0.69897000433601885749
#define M_2PI 6.28318530717958623200
#define LOG_MIN 1.0e-100
#define LOG_MAX 1.0e100
#define M_E 2.7182818284590452354
#define M_LOG2E 1.4426950408889634074
#define M_LN2 0.69314718055994530942
#define M_LN10 2.30258509299404568402
#define M_PI 3.14159265358979323846
#define M_PI_2 1.57079632679489661923
#define M_PI_4 0.78539816339744830962
#define M_1_PI 0.31830988618379067154
#define M_2_PI 0.63661977236758134308
#define M_2_SQRTPI 1.12837916709551257390
#define M_SQRT2 1.41421356237309504880
#define M_SQRT1_2 0.70710678118654752440
Functions
QWT_EXPORT double qwtGetMin (const double *array, int size)
QWT_EXPORT double qwtGetMax (const double *array, int size)
int qwtSign (double x)
double qwtSqr (const double x)
template<class T> T qwtLim (const T &x, const T &x1, const T &x2)
QPoint qwtPolar2Pos (const QPoint &center, double radius, double angle)
QPoint qwtDegree2Pos (const QPoint &center, double radius, double angle)
Define Documentation
#define LOG_MAX 1.0e100
Maximum value for logarithmic scales.
Definition at line 59 of file qwt_math.h.
Referenced by QwtLog10ScaleEngine::autoScale(), and QwtLog10ScaleEngine::divideScale().
#define LOG_MIN 1.0e-100
Mininum value for logarithmic scales.
Definition at line 54 of file qwt_math.h.
Referenced by QwtLog10ScaleEngine::autoScale(), and QwtLog10ScaleEngine::divideScale().
Function Documentation
QWT_EXPORT double qwtGetMax (const double * array, int size)
Find the largest value in an array.
Parameters:
array Pointer to an array
size Array size
Definition at line 37 of file qwt_math.cpp.
References qwtMax.
QWT_EXPORT double qwtGetMin (const double * array, int size)
Find the smallest value in an array.
Parameters:
array Pointer to an array
size Array size
Definition at line 19 of file qwt_math.cpp.
References qwtMin.
template<class T> T qwtLim (const T & x, const T & x1, const T & x2)
Limit a value to fit into a specified interval.
Parameters:
x Input value
x1 First interval boundary
x2 Second interval boundary
Definition at line 142 of file qwt_math.h.
References qwtMax, and qwtMin.
Referenced by QwtArrowButton::QwtArrowButton(), QwtRoundScaleDraw::setAngleRange(), QwtDoubleRange::setRange(), QwtWheel::setTickCnt(), and QwtWheel::setViewAngle().
int qwtSign (double x)
Return the sign.
Definition at line 119 of file qwt_math.h.
double qwtSqr (const double x)
Return the square of a number.
Definition at line 130 of file qwt_math.h.
Referenced by QwtSpline::buildPeriodicSpline(), and QwtPlotCurve::closestPoint().
Author
Generated automatically by Doxygen for Qwt User's Guide from the source code.