.TH "QwtArrowButton" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtArrowButton \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Arrow Button. 

A push button with one or more filled triangles on its front. An Arrow button can have 1 to 3 arrows in a row, pointing up, down, left or right.
.PP
Definition at line 23 of file qwt_arrow_button.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtArrowButton\fP (int num, Qt::ArrowType, QWidget *parent=NULL)"
.br
.ti -1c
.RI "virtual \fB~QwtArrowButton\fP ()"
.br
.ti -1c
.RI "Qt::ArrowType \fBarrowType\fP () const "
.br
.ti -1c
.RI "int \fBnum\fP () const "
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "virtual QSize \fBminimumSizeHint\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "virtual void \fBdrawButtonLabel\fP (QPainter *p)"
.br
.ti -1c
.RI "virtual void \fBdrawArrow\fP (QPainter *, const QRect &, Qt::ArrowType) const "
.br
.ti -1c
.RI "virtual QRect \fBlabelRect\fP () const "
.br
.ti -1c
.RI "virtual QSize \fBarrowSize\fP (Qt::ArrowType, const QSize &boundingSize) const "
.br
.ti -1c
.RI "virtual void \fBkeyPressEvent\fP (QKeyEvent *)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtArrowButton::QwtArrowButton (int num, Qt::ArrowType arrowType, QWidget * parent = \fCNULL\fP)\fC [explicit]\fP"
.PP
\fBParameters:\fP
.RS 4
\fInum\fP Number of arrows 
.br
\fIarrowType\fP see Qt::ArowType in the Qt docs. 
.br
\fIparent\fP Parent widget
.RE
.PP

.PP
Definition at line 58 of file qwt_arrow_button.cpp.
.PP
References qwtLim().
.SH "Member Function Documentation"
.PP 
.SS "QSize QwtArrowButton::arrowSize (Qt::ArrowType arrowType, const QSize & boundingSize) const\fC [protected, virtual]\fP"
.PP
Calculate the size for a arrow that fits into a rect of a given size
.PP
\fBParameters:\fP
.RS 4
\fIarrowType\fP Arrow type 
.br
\fIboundingSize\fP Bounding size 
.RE
.PP
\fBReturns:\fP
.RS 4
Size of the arrow
.RE
.PP

.PP
Definition at line 319 of file qwt_arrow_button.cpp.
.PP
Referenced by drawButtonLabel(), and minimumSizeHint().
.SS "Qt::ArrowType QwtArrowButton::arrowType () const"
.PP
The direction of the arrows. 
.PP
Definition at line 91 of file qwt_arrow_button.cpp.
.SS "void QwtArrowButton::drawArrow (QPainter * p, const QRect & r, Qt::ArrowType arrowType) const\fC [protected, virtual]\fP"
.PP
Draw an arrow int a bounding rect
.PP
\fBParameters:\fP
.RS 4
\fIp\fP Painter 
.br
\fIr\fP Rectangle where to paint the arrow 
.br
\fIarrowType\fP Arrow type
.RE
.PP

.PP
Definition at line 233 of file qwt_arrow_button.cpp.
.PP
Referenced by drawButtonLabel().
.SS "void QwtArrowButton::drawButtonLabel (QPainter * p)\fC [protected, virtual]\fP"
.PP
Draw the button label. 
.PP
\fBSee also:\fP
.RS 4
The Qt Manual on QPushButton
.RE
.PP

.PP
Definition at line 150 of file qwt_arrow_button.cpp.
.PP
References arrowSize(), drawArrow(), labelRect(), and num().
.PP
Referenced by paintEvent().
.SS "void QwtArrowButton::keyPressEvent (QKeyEvent *)\fC [protected, virtual]\fP"
.PP
autoRepeat for the space keys 
.PP
Definition at line 349 of file qwt_arrow_button.cpp.
.SS "QRect QwtArrowButton::labelRect () const\fC [protected, virtual]\fP"
.PP
\fBReturns:\fP
.RS 4
the bounding rect for the label
.RE
.PP

.PP
Definition at line 107 of file qwt_arrow_button.cpp.
.PP
Referenced by drawButtonLabel().
.SS "QSize QwtArrowButton::minimumSizeHint () const\fC [virtual]\fP"
.PP
Return a minimum size hint. 
.PP
Definition at line 287 of file qwt_arrow_button.cpp.
.PP
References arrowSize().
.PP
Referenced by sizeHint().
.SS "int QwtArrowButton::num () const"
.PP
The number of arrows. 
.PP
Definition at line 99 of file qwt_arrow_button.cpp.
.PP
Referenced by drawButtonLabel().
.SS "QSize QwtArrowButton::sizeHint () const\fC [virtual]\fP"
.PP
\fBReturns:\fP
.RS 4
a size hint
.RE
.PP

.PP
Definition at line 279 of file qwt_arrow_button.cpp.
.PP
References minimumSizeHint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
