.TH "QwtCompassRose" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtCompassRose \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBQwtSimpleCompassRose\fP.
.PP
.SH "Detailed Description"
.PP 
Abstract base class for a compass rose. 
.PP
Definition at line 21 of file qwt_compass_rose.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~QwtCompassRose\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetPalette\fP (const QPalette &p)"
.br
.ti -1c
.RI "const QPalette & \fBpalette\fP () const "
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *painter, const QPoint &center, int radius, double north, QPalette::ColorGroup colorGroup=QPalette::Active) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void QwtCompassRose::draw (QPainter * painter, const QPoint & center, int radius, double north, QPalette::ColorGroup colorGroup = \fCQPalette::Active\fP) const\fC [pure virtual]\fP"
.PP
Draw the rose
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIcenter\fP Center point 
.br
\fIradius\fP Radius of the rose 
.br
\fInorth\fP Position 
.br
\fIcolorGroup\fP Color group
.RE
.PP

.PP
Implemented in \fBQwtSimpleCompassRose\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
