.TH "QwtCurveFitter" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtCurveFitter \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBQwtSplineCurveFitter\fP.
.PP
.SH "Detailed Description"
.PP 
Abstract base class for a curve fitter. 
.PP
Definition at line 39 of file qwt_curve_fitter.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~QwtCurveFitter\fP ()"
.br
.ti -1c
.RI "virtual QPolygonF \fBfitCurve\fP (const QPolygonF &) const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtCurveFitter\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
