QwtCompassMagnetNeedle
NAME
QwtCompassMagnetNeedle -
SYNOPSIS
Inherits QwtDialNeedle.
Detailed Description
A magnet needle for compass widgets.
A magnet needle points to two opposite directions indicating north and south.
The following colors are used:
QColorGroup::Light
 Used for pointing south
QColorGroup::Dark
 Used for pointing north
QColorGroup::Base
 Knob (ThinStyle only)
See also:
QwtDial, QwtCompass
Definition at line 124 of file qwt_dial_needle.h.
Public Types
enum Style { TriangleStyle, ThinStyle }
Public Member Functions
QwtCompassMagnetNeedle (Style=TriangleStyle, const QColor &light=Qt::white, const QColor &dark=Qt::red)
virtual void draw (QPainter *, const QPoint &, int length, double direction, QPalette::ColorGroup=QPalette::Active) const
Static Public Member Functions
static void drawTriangleNeedle (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)
static void drawThinNeedle (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)
Static Protected Member Functions
static void drawPointer (QPainter *painter, const QBrush &brush, int colorOffset, const QPoint &center, int length, int width, double direction)
Constructor & Destructor Documentation
QwtCompassMagnetNeedle::QwtCompassMagnetNeedle (Style = TriangleStyle, const QColor & light = Qt::white, const QColor & dark = Qt::red)
Constructor.
Definition at line 265 of file qwt_dial_needle.cpp.
References QwtDialNeedle::palette(), and QwtDialNeedle::setPalette().
Member Function Documentation
void QwtCompassMagnetNeedle::draw (QPainter * painter, const QPoint & center, int length, double direction, QPalette::ColorGroup colorGroup = QPalette::Active) const [virtual]
Draw the needle
Parameters:
painter Painter
center Center of the dial, start position for the needle
length Length of the needle
direction Direction of the needle, in degrees counter clockwise
colorGroup Color group, used for painting
Implements QwtDialNeedle.
Definition at line 292 of file qwt_dial_needle.cpp.
References drawThinNeedle(), drawTriangleNeedle(), and QwtDialNeedle::palette().
void QwtCompassMagnetNeedle::drawPointer (QPainter * painter, const QBrush & brush, int colorOffset, const QPoint & center, int length, int width, double direction) [static, protected]
Draw a compass needle
Definition at line 397 of file qwt_dial_needle.cpp.
References qwtDegree2Pos(), and qwtMax.
Referenced by drawThinNeedle().
void QwtCompassMagnetNeedle::drawThinNeedle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction) [static]
Draw a compass needle
Definition at line 369 of file qwt_dial_needle.cpp.
References QwtDialNeedle::drawKnob(), drawPointer(), and qwtMax.
Referenced by draw().
void QwtCompassMagnetNeedle::drawTriangleNeedle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction) [static]
Draw a compass needle
Definition at line 310 of file qwt_dial_needle.cpp.
References qwtDegree2Pos().
Referenced by draw().
Author
Generated automatically by Doxygen for Qwt User's Guide from the source code.