QwtCompassWindArrow
NAME
QwtCompassWindArrow -
SYNOPSIS
Inherits QwtDialNeedle.
Detailed Description
An indicator for the wind direction.
QwtCompassWindArrow shows the direction where the wind comes from.
QColorGroup::Light
 Used for Style1, or the light half of Style2
QColorGroup::Dark
 Used for the dark half of Style2
See also:
QwtDial, QwtCompass
Definition at line 168 of file qwt_dial_needle.h.
Public Types
enum Style { Style1, Style2 }
Public Member Functions
QwtCompassWindArrow (Style, const QColor &light=Qt::white, const QColor &dark=Qt::gray)
virtual void draw (QPainter *, const QPoint &, int length, double direction, QPalette::ColorGroup=QPalette::Active) const
Static Public Member Functions
static void drawStyle1Needle (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)
static void drawStyle2Needle (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)
Constructor & Destructor Documentation
QwtCompassWindArrow::QwtCompassWindArrow (Style, const QColor & light = Qt::white, const QColor & dark = Qt::gray)
Constructor.
Definition at line 440 of file qwt_dial_needle.cpp.
References QwtDialNeedle::palette(), and QwtDialNeedle::setPalette().
Member Function Documentation
void QwtCompassWindArrow::draw (QPainter * painter, const QPoint & center, int length, double direction, QPalette::ColorGroup colorGroup = QPalette::Active) const [virtual]
Draw the needle
Parameters:
painter Painter
center Center of the dial, start position for the needle
length Length of the needle
direction Direction of the needle, in degrees counter clockwise
colorGroup Color group, used for painting
Implements QwtDialNeedle.
Definition at line 465 of file qwt_dial_needle.cpp.
References drawStyle1Needle(), drawStyle2Needle(), and QwtDialNeedle::palette().
void QwtCompassWindArrow::drawStyle1Needle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction) [static]
Draw a compass needle
Definition at line 483 of file qwt_dial_needle.cpp.
References qwtDegree2Pos().
Referenced by draw().
void QwtCompassWindArrow::drawStyle2Needle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction) [static]
Draw a compass needle
Definition at line 513 of file qwt_dial_needle.cpp.
References qwtDegree2Pos().
Referenced by draw().
Author
Generated automatically by Doxygen for Qwt User's Guide from the source code.