.TH "QwtEventPattern::MousePattern" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::MousePattern \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 136 of file qwt_event_pattern.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMousePattern\fP (int btn=Qt::NoButton, int st=Qt::NoButton)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbutton\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
