.TH "QwtIntervalData" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtIntervalData \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Interval data class. 
.PP
Definition at line 34 of file qwt_interval_data.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtIntervalData\fP ()"
.br
.ti -1c
.RI "\fBQwtIntervalData\fP (const QwtArray< \fBQwtDoubleInterval\fP > &, const QwtArray< double > &)"
.br
.ti -1c
.RI "void \fBsetData\fP (const QwtArray< \fBQwtDoubleInterval\fP > &, const QwtArray< double > &)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "const \fBQwtDoubleInterval\fP & \fBinterval\fP (size_t i) const "
.br
.ti -1c
.RI "double \fBvalue\fP (size_t i) const "
.br
.ti -1c
.RI "QwtDoubleRect \fBboundingRect\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
