.TH "QwtLegend" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtLegend \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The legend widget. 

The QwtLegend widget is a tabular arrangement of legend items. Legend items might be any type of widget, but in general they will be a \fBQwtLegendItem\fP.
.PP
\fBSee also:\fP
.RS 4
\fBQwtLegendItem\fP, \fBQwtPlot\fP
.RE
.PP

.PP
Definition at line 36 of file qwt_legend.h.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLegendDisplayPolicy\fP { \fBNone\fP =  0, \fBFixed\fP =  1, \fBAuto\fP =  2 }"
.br
.ti -1c
.RI "enum \fBLegendItemMode\fP { \fBReadOnlyItem\fP, \fBClickableItem\fP, \fBCheckableItem\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtLegend\fP (QWidget *parent=NULL)"
.br
.ti -1c
.RI "virtual \fB~QwtLegend\fP ()"
.br
.ti -1c
.RI "void \fBsetDisplayPolicy\fP (\fBLegendDisplayPolicy\fP policy, int mode=-1)"
.br
.ti -1c
.RI "\fBLegendDisplayPolicy\fP \fBdisplayPolicy\fP () const "
.br
.ti -1c
.RI "void \fBsetItemMode\fP (\fBLegendItemMode\fP)"
.br
.ti -1c
.RI "\fBLegendItemMode\fP \fBitemMode\fP () const "
.br
.ti -1c
.RI "int \fBidentifierMode\fP () const "
.br
.ti -1c
.RI "QWidget * \fBcontentsWidget\fP ()"
.br
.ti -1c
.RI "const QWidget * \fBcontentsWidget\fP () const "
.br
.ti -1c
.RI "void \fBinsert\fP (const \fBQwtPlotItem\fP *, QWidget *)"
.br
.ti -1c
.RI "void \fBremove\fP (const \fBQwtPlotItem\fP *)"
.br
.ti -1c
.RI "QWidget * \fBfind\fP (const \fBQwtPlotItem\fP *) const "
.br
.ti -1c
.RI "\fBQwtPlotItem\fP * \fBfind\fP (const QWidget *) const "
.br
.ti -1c
.RI "virtual QList< QWidget * > \fBlegendItems\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const "
.br
.ti -1c
.RI "uint \fBitemCount\fP () const "
.br
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "virtual int \fBheightForWidth\fP (int w) const "
.br
.ti -1c
.RI "QScrollBar * \fBhorizontalScrollBar\fP () const "
.br
.ti -1c
.RI "QScrollBar * \fBverticalScrollBar\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBresizeEvent\fP (QResizeEvent *)"
.br
.ti -1c
.RI "virtual void \fBlayoutContents\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQwtLegend::LegendDisplayPolicy\fP"
.PP
Display policy. 
.PP
.IP "\(bu" 2
None
.br
 the client code is responsible how to display of each legend item. The Qwt library will not interfere.
.PP
.PP
.IP "\(bu" 2
Fixed
.br
 all legend items are displayed with the \fBQwtLegendItem::IdentifierMode\fP to be passed in 'mode'.
.PP
.PP
.IP "\(bu" 2
Auto
.br
 each legend item is displayed with a mode that is a bitwise or of
.IP "  \(bu" 4
QwtLegendItem::ShowLine (if its curve is drawn with a line) and
.IP "  \(bu" 4
QwtLegendItem::ShowSymbol (if its curve is drawn with symbols) and
.IP "  \(bu" 4
QwtLegendItem::ShowText (if the has a title).
.PP

.PP
.PP
Default is LegendDisplayPolicy::Auto. 
.PP
\fBSee also:\fP
.RS 4
\fBQwtLegend::setDisplayPolicy\fP, \fBQwtLegend::displayPolicy\fP, \fBQwtLegendItem::IdentifierMode\fP
.RE
.PP

.PP
Definition at line 62 of file qwt_legend.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtLegend::QwtLegend (QWidget * parent = \fCNULL\fP)\fC [explicit]\fP"
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP Parent widget
.RE
.PP

.PP
Definition at line 237 of file qwt_legend.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void QwtLegend::clear ()"
.PP
Remove all items. 
.PP
Definition at line 451 of file qwt_legend.cpp.
.SS "const QWidget * QwtLegend::contentsWidget () const"
.PP
The contents widget is the only child of the viewport() and the parent widget of all legend items.
.PP
Definition at line 353 of file qwt_legend.cpp.
.SS "QWidget * QwtLegend::contentsWidget ()"
.PP
The contents widget is the only child of the viewport() and the parent widget of all legend items.
.PP
Definition at line 333 of file qwt_legend.cpp.
.PP
Referenced by insert(), and QwtPlot::printLegend().
.SS "\fBQwtLegend::LegendDisplayPolicy\fP QwtLegend::displayPolicy () const"
.PP
\fBReturns:\fP
.RS 4
the legend display policy. Default is LegendDisplayPolicy::Auto. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBsetDisplayPolicy\fP, \fBLegendDisplayPolicy\fP
.RE
.PP

.PP
Definition at line 302 of file qwt_legend.cpp.
.PP
Referenced by QwtPlotCurve::updateLegend().
.SS "int QwtLegend::heightForWidth (int w) const\fC [virtual]\fP"
.PP
\fBReturns:\fP
.RS 4
The preferred height, for the width w.
.RE
.PP

.PP
Definition at line 478 of file qwt_legend.cpp.
.PP
Referenced by QwtPlotLayout::minimumSizeHint().
.SS "int QwtLegend::identifierMode () const"
.PP
\fBReturns:\fP
.RS 4
the IdentifierMode to be used in combination with LegendDisplayPolicy::Fixed.
.RE
.PP
Default is ShowLine | ShowSymbol | ShowText.
.PP
Definition at line 324 of file qwt_legend.cpp.
.PP
Referenced by QwtPlotCurve::updateLegend().
.SS "void QwtLegend::insert (const \fBQwtPlotItem\fP * plotItem, QWidget * legendItem)"
.PP
Insert a new item for a plot item 
.PP
\fBParameters:\fP
.RS 4
\fIplotItem\fP Plot item 
.br
\fIlegendItem\fP New legend item 
.RE
.PP
\fBNote:\fP
.RS 4
The parent of item will be changed to \fBQwtLegend::contentsWidget()\fP
.RE
.PP

.PP
Definition at line 364 of file qwt_legend.cpp.
.PP
References contentsWidget(), and layoutContents().
.PP
Referenced by QwtPlotItem::updateLegend().
.SS "bool QwtLegend::isEmpty () const"
.PP
Return true, if there are no legend items. 
.PP
Definition at line 574 of file qwt_legend.cpp.
.PP
Referenced by QwtPlotLayout::activate(), QwtPlotLayout::minimumSizeHint(), and QwtPlot::print().
.SS "uint QwtLegend::itemCount () const"
.PP
Return the number of legend items. 
.PP
Definition at line 580 of file qwt_legend.cpp.
.SS "void QwtLegend::layoutContents ()\fC [protected, virtual]\fP"
.PP
Adjust contents widget and item layout to the size of the viewport().
.PP
Definition at line 503 of file qwt_legend.cpp.
.PP
References QwtDynGridLayout::heightForWidth(), QwtDynGridLayout::maxItemWidth(), and qwtMax.
.PP
Referenced by eventFilter(), and insert().
.SS "void QwtLegend::remove (const \fBQwtPlotItem\fP *)"
.PP
Find the corresponding item for a plotItem and remove it from the item list. 
.PP
Definition at line 443 of file qwt_legend.cpp.
.SS "void QwtLegend::setDisplayPolicy (\fBLegendDisplayPolicy\fP policy, int mode = \fC-1\fP)"
.PP
Set the legend display policy to:
.PP
\fBParameters:\fP
.RS 4
\fIpolicy\fP Legend display policy 
.br
\fImode\fP Identifier mode (or'd ShowLine, ShowSymbol, ShowText)
.RE
.PP
\fBSee also:\fP
.RS 4
\fBdisplayPolicy\fP, \fBLegendDisplayPolicy\fP
.RE
.PP

.PP
Definition at line 274 of file qwt_legend.cpp.
.PP
References QwtPlotItem::updateLegend().
.SS "QSize QwtLegend::sizeHint () const\fC [virtual]\fP"
.PP
Return a size hint. 
.PP
Definition at line 467 of file qwt_legend.cpp.
.PP
Referenced by QwtPlotLayout::minimumSizeHint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
