QwtPlotItem
NAME
QwtPlotItem -
SYNOPSIS
Inherited by QwtPlotCurve, QwtPlotGrid, QwtPlotMarker, QwtPlotRasterItem, and QwtPlotSvgItem.
Detailed Description
Base class for items on the plot canvas.
Definition at line 30 of file qwt_plot_item.h.
Public Types
enum RttiValues { Rtti_PlotItem = 0, Rtti_PlotGrid, Rtti_PlotMarker, Rtti_PlotCurve, Rtti_PlotHistogram, Rtti_PlotSpectrogram, Rtti_PlotSVG, Rtti_PlotUserItem = 1000 }
enum ItemAttribute { Legend = 1, AutoScale = 2 }
enum RenderHint { RenderAntialiased = 1 }
Public Member Functions
QwtPlotItem (const QwtText &title=QwtText())
virtual ~QwtPlotItem ()
void attach (QwtPlot *plot)
void detach ()
QwtPlot * plot () const
void setTitle (const QString &title)
void setTitle (const QwtText &title)
const QwtText & title () const
virtual int rtti () const
void setItemAttribute (ItemAttribute, bool on=true)
bool testItemAttribute (ItemAttribute) const
void setRenderHint (RenderHint, bool on=true)
bool testRenderHint (RenderHint) const
double z () const
void setZ (double z)
void show ()
void hide ()
virtual void setVisible (bool)
bool isVisible () const
void setAxis (int xAxis, int yAxis)
void setXAxis (int axis)
int xAxis () const
void setYAxis (int axis)
int yAxis () const
virtual void itemChanged ()
virtual void draw (QPainter *painter, const QwtScaleMap &xMap, const QwtScaleMap &yMap, const QRect &canvasRect) const =0
virtual QwtDoubleRect boundingRect () const
virtual void updateLegend (QwtLegend *) const
virtual void updateScaleDiv (const QwtScaleDiv &, const QwtScaleDiv &)
virtual QWidget * legendItem () const
QwtDoubleRect scaleRect (const QwtScaleMap &, const QwtScaleMap &) const
QRect paintRect (const QwtScaleMap &, const QwtScaleMap &) const
QRect transform (const QwtScaleMap &, const QwtScaleMap &, const QwtDoubleRect &) const
QwtDoubleRect invTransform (const QwtScaleMap &, const QwtScaleMap &, const QRect &) const
Constructor & Destructor Documentation
QwtPlotItem::QwtPlotItem (const QwtText & title = QwtText()) [explicit]
Constructor.
Definition at line 48 of file qwt_plot_item.cpp.
QwtPlotItem::~QwtPlotItem () [virtual]
Destroy the QwtPlotItem.
Definition at line 55 of file qwt_plot_item.cpp.
References attach().
Member Function Documentation
void QwtPlotItem::attach (QwtPlot * plot)
Attach the item to a plot
Definition at line 64 of file qwt_plot_item.cpp.
References itemChanged(), and legendItem().
Referenced by ~QwtPlotItem().
virtual void QwtPlotItem::draw (QPainter * painter, const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRect & canvasRect) const [pure virtual]
Draw the item.
Parameters:
painter Painter
xMap Maps x-values into pixel coordinates.
yMap Maps y-values into pixel coordinates.
canvasRect Contents rect of the canvas in painter coordinates
Implemented in QwtPlotCurve, QwtPlotGrid, QwtPlotMarker, QwtPlotRasterItem, QwtPlotSpectrogram, and QwtPlotSvgItem.
Referenced by QwtPlot::drawItems().
bool QwtPlotItem::isVisible () const
Returns:
true if enabled
See also:
QwtPlotItem::setEnabled
Definition at line 229 of file qwt_plot_item.cpp.
Referenced by QwtPlot::drawItems().
void QwtPlotItem::itemChanged () [virtual]
Call QwtPlot::autoRefresh for the parent plot.
Definition at line 235 of file qwt_plot_item.cpp.
References updateLegend().
Referenced by attach(), QwtPlotGrid::enableX(), QwtPlotGrid::enableXMin(), QwtPlotGrid::enableY(), QwtPlotGrid::enableYMin(), QwtPlotSvgItem::loadData(), QwtPlotSvgItem::loadFile(), QwtPlotRasterItem::setAlpha(), setAxis(), QwtPlotCurve::setBaseline(), QwtPlotCurve::setBrush(), QwtPlotRasterItem::setCachePolicy(), QwtPlotSpectrogram::setColorMap(), QwtPlotSpectrogram::setConrecAttribute(), QwtPlotSpectrogram::setContourLevels(), QwtPlotCurve::setCurveAttribute(), QwtPlotCurve::setCurveFitter(), QwtPlotCurve::setCurveType(), QwtPlotSpectrogram::setData(), QwtPlotCurve::setData(), QwtPlotSpectrogram::setDefaultContourPen(), QwtPlotSpectrogram::setDisplayMode(), setItemAttribute(), QwtPlotMarker::setLabel(), QwtPlotMarker::setLinePen(), QwtPlotMarker::setLineStyle(), QwtPlotGrid::setMajPen(), QwtPlotGrid::setMinPen(), QwtPlotGrid::setPen(), QwtPlotCurve::setPen(), QwtPlotCurve::setRawData(), setRenderHint(), QwtPlotCurve::setStyle(), QwtPlotMarker::setSymbol(), QwtPlotCurve::setSymbol(), setTitle(), QwtPlotMarker::setValue(), setVisible(), setXAxis(), QwtPlotGrid::setXDiv(), setYAxis(), QwtPlotGrid::setYDiv(), and setZ().
QwtPlot * QwtPlotItem::plot () const
Return attached plot.
Definition at line 103 of file qwt_plot_item.cpp.
Referenced by QwtPlotCurve::closestPoint(), and QwtPlotCurve::draw().
void QwtPlotItem::setAxis (int xAxis, int yAxis)
Set x and y axis.
Definition at line 247 of file qwt_plot_item.cpp.
References itemChanged().
void QwtPlotItem::setTitle (const QwtText & title)
Set a new title
Parameters:
title Title
See also:
title()
Definition at line 145 of file qwt_plot_item.cpp.
References itemChanged().
void QwtPlotItem::setTitle (const QString & title)
Set a new title
Parameters:
title Title
See also:
title()
Definition at line 134 of file qwt_plot_item.cpp.
void QwtPlotItem::setVisible (bool on) [virtual]
See also:
QwtPlotItem::setVisible
Definition at line 216 of file qwt_plot_item.cpp.
References itemChanged().
Referenced by hide(), and show().
void QwtPlotItem::setXAxis (int axis)
Set y axis.
Definition at line 259 of file qwt_plot_item.cpp.
References itemChanged().
void QwtPlotItem::setYAxis (int axis)
Set y axis.
Definition at line 269 of file qwt_plot_item.cpp.
References itemChanged().
const QwtText & QwtPlotItem::title () const
Returns:
Title of the item
See also:
setTitle()
Definition at line 158 of file qwt_plot_item.cpp.
Referenced by QwtPlotCurve::updateLegend().
int QwtPlotItem::xAxis () const
Return xAxis.
Definition at line 279 of file qwt_plot_item.cpp.
Referenced by QwtPlotCurve::closestPoint(), QwtPlotCurve::draw(), QwtPlot::drawItems(), and QwtPlot::updateAxes().
int QwtPlotItem::yAxis () const
Return yAxis.
Definition at line 285 of file qwt_plot_item.cpp.
Referenced by QwtPlotCurve::closestPoint(), QwtPlotCurve::draw(), QwtPlot::drawItems(), and QwtPlot::updateAxes().
Author
Generated automatically by Doxygen for Qwt User's Guide from the source code.