.TH "QwtRect" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtRect \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Some extensions for QRect. 
.PP
Definition at line 21 of file qwt_rect.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtRect\fP ()"
.br
.ti -1c
.RI "\fBQwtRect\fP (const QRect &r)"
.br
.ti -1c
.RI "QwtPolygon \fBclip\fP (const QwtPolygon &) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtRect::QwtRect ()"
.PP
Constructor. 
.PP
Definition at line 15 of file qwt_rect.cpp.
.SS "QwtRect::QwtRect (const QRect & r)"
.PP
Copy constructor. 
.PP
Definition at line 21 of file qwt_rect.cpp.
.SH "Member Function Documentation"
.PP 
.SS "QwtPolygon QwtRect::clip (const QwtPolygon &) const"
.PP
Sutherland-Hodgman polygon clipping. 
.PP
Definition at line 36 of file qwt_rect.cpp.
.PP
Referenced by QwtPainter::clip(), QwtPlotCurve::drawDots(), QwtPlotCurve::drawLines(), and QwtPlotCurve::drawSteps().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
