.TH "QwtScaleDiv" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtScaleDiv \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A class representing a scale division. 

A scale division consists of its limits and 3 list of tick values qualified as major, medium and minor ticks.
.PP
In most cases scale divisions are calculated by a \fBQwtScaleEngine\fP.
.PP
\fBSee also:\fP
.RS 4
QwtScaleEngine::subDivideInto, QwtScaleEngine::subDivide
.RE
.PP

.PP
Definition at line 29 of file qwt_scale_div.h.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTickType\fP { \fBNoTick\fP =  -1, \fBMinorTick\fP, \fBMediumTick\fP, \fBMajorTick\fP, \fBNTickTypes\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtScaleDiv\fP ()"
.br
.ti -1c
.RI "\fBQwtScaleDiv\fP (const \fBQwtDoubleInterval\fP &, QwtValueList[NTickTypes])"
.br
.ti -1c
.RI "\fBQwtScaleDiv\fP (double lBound, double rBound, QwtValueList[NTickTypes])"
.br
.ti -1c
.RI "int \fBoperator==\fP (const \fBQwtScaleDiv\fP &s) const "
.br
.ti -1c
.RI "int \fBoperator!=\fP (const \fBQwtScaleDiv\fP &s) const "
.br
.ti -1c
.RI "double \fBlBound\fP () const "
.br
.ti -1c
.RI "double \fBhBound\fP () const "
.br
.ti -1c
.RI "double \fBrange\fP () const "
.br
.ti -1c
.RI "bool \fBcontains\fP (double v) const "
.br
.ti -1c
.RI "const QwtValueList & \fBticks\fP (int type) const "
.br
.ti -1c
.RI "void \fBinvalidate\fP ()"
.br
.ti -1c
.RI "bool \fBisValid\fP () const "
.br
.ti -1c
.RI "void \fBinvert\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtScaleDiv::QwtScaleDiv ()\fC [explicit]\fP"
.PP
Construct an invalid QwtScaleDiv instance. 
.PP
Definition at line 15 of file qwt_scale_div.cpp.
.SS "QwtScaleDiv::QwtScaleDiv (const \fBQwtDoubleInterval\fP & interval, QwtValueList ticks[NTickTypes])\fC [explicit]\fP"
.PP
Construct QwtScaleDiv instance.
.PP
\fBParameters:\fP
.RS 4
\fIinterval\fP Interval 
.br
\fIticks\fP List of major, medium and minor ticks
.RE
.PP

.PP
Definition at line 28 of file qwt_scale_div.cpp.
.PP
References ticks().
.SS "QwtScaleDiv::QwtScaleDiv (double lBound, double hBound, QwtValueList ticks[NTickTypes])\fC [explicit]\fP"
.PP
Construct QwtScaleDiv instance.
.PP
\fBParameters:\fP
.RS 4
\fIlBound\fP First interval limit 
.br
\fIhBound\fP Second interval limit 
.br
\fIticks\fP List of major, medium and minor ticks
.RE
.PP

.PP
Definition at line 46 of file qwt_scale_div.cpp.
.PP
References ticks().
.SH "Member Function Documentation"
.PP 
.SS "double QwtScaleDiv::hBound () const"
.PP
\fBReturns:\fP
.RS 4
right bound 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtScaleDiv::lBound\fP
.RE
.PP

.PP
Definition at line 86 of file qwt_scale_div.h.
.PP
Referenced by QwtPlot::canvasMap(), QwtPlotPanner::moveCanvas(), QwtPlot::print(), QwtPlotZoomer::rescale(), and QwtAbstractScaleDraw::setScaleDiv().
.SS "void QwtScaleDiv::invalidate ()"
.PP
Invalidate the scale division. 
.PP
Definition at line 89 of file qwt_scale_div.cpp.
.SS "void QwtScaleDiv::invert ()"
.PP
Invert the scale divison. 
.PP
Definition at line 118 of file qwt_scale_div.cpp.
.PP
References ticks().
.PP
Referenced by QwtLog10ScaleEngine::divideScale(), and QwtLinearScaleEngine::divideScale().
.SS "bool QwtScaleDiv::isValid () const"
.PP
Check if the scale division is valid. 
.PP
Definition at line 101 of file qwt_scale_div.cpp.
.PP
Referenced by QwtPlotMagnifier::rescale().
.SS "double QwtScaleDiv::lBound () const"
.PP
\fBReturns:\fP
.RS 4
left bound 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtScaleDiv::hBound\fP
.RE
.PP

.PP
Definition at line 77 of file qwt_scale_div.h.
.PP
Referenced by QwtPlot::canvasMap(), QwtPlotPanner::moveCanvas(), QwtPlot::print(), QwtPlotZoomer::rescale(), QwtPlotMagnifier::rescale(), QwtPlotPicker::scaleRect(), and QwtAbstractScaleDraw::setScaleDiv().
.SS "int QwtScaleDiv::operator!= (const \fBQwtScaleDiv\fP & s) const"
.PP
Inequality. 
.PP
\fBReturns:\fP
.RS 4
true if this instance is not equal to s
.RE
.PP

.PP
Definition at line 83 of file qwt_scale_div.cpp.
.SS "int QwtScaleDiv::operator== (const \fBQwtScaleDiv\fP & other) const"
.PP
Equality operator. 
.PP
\fBReturns:\fP
.RS 4
true if this instance is equal to other
.RE
.PP

.PP
Definition at line 61 of file qwt_scale_div.cpp.
.PP
References d_hBound, d_isValid, d_lBound, and d_ticks.
.SS "double QwtScaleDiv::range () const"
.PP
\fBReturns:\fP
.RS 4
\fBhBound()\fP - \fBlBound()\fP
.RE
.PP

.PP
Definition at line 94 of file qwt_scale_div.h.
.PP
Referenced by QwtPlotMagnifier::rescale(), and QwtPlotPicker::scaleRect().
.SS "const QwtValueList & QwtScaleDiv::ticks (int type) const"
.PP
Return a list of ticks
.PP
\fBParameters:\fP
.RS 4
\fItype\fP MinorTick, MediumTick or MajorTick
.RE
.PP

.PP
Definition at line 139 of file qwt_scale_div.cpp.
.PP
Referenced by QwtRoundScaleDraw::extent(), QwtScaleDraw::getBorderDistHint(), invert(), QwtScaleDraw::maxLabelHeight(), QwtScaleDraw::maxLabelWidth(), QwtScaleDraw::minLabelDist(), QwtScaleDraw::minLength(), QwtScaleDiv(), and QwtPlot::sizeHint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
