.TH "QwtSlider" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtSlider \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBQwtAbstractSlider\fP, and \fBQwtAbstractScale\fP.
.PP
.SH "Detailed Description"
.PP 
The Slider Widget. 

QwtSlider is a slider widget which operates on an interval of type double. QwtSlider supports different layouts as well as a scale.
.PP
.PP
\fBSee also:\fP
.RS 4
\fBQwtAbstractSlider\fP and \fBQwtAbstractScale\fP for the descriptions of the inherited members.
.RE
.PP

.PP
Definition at line 34 of file qwt_slider.h.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBScalePos\fP { \fBNone\fP, \fBLeft\fP, \fBRight\fP, \fBTop\fP, \fBBottom\fP }"
.br
.ti -1c
.RI "enum \fBBGSTYLE\fP { \fBBgTrough\fP =  0x1, \fBBgSlot\fP =  0x2, \fBBgBoth\fP =  BgTrough | BgSlot }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtSlider\fP (QWidget *parent, Qt::Orientation=Qt::Horizontal, \fBScalePos\fP=None, \fBBGSTYLE\fP bgStyle=BgTrough)"
.br
.ti -1c
.RI "virtual \fB~QwtSlider\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetOrientation\fP (Qt::Orientation)"
.br
.ti -1c
.RI "void \fBsetBgStyle\fP (\fBBGSTYLE\fP)"
.br
.ti -1c
.RI "\fBBGSTYLE\fP \fBbgStyle\fP () const "
.br
.ti -1c
.RI "void \fBsetScalePosition\fP (\fBScalePos\fP s)"
.br
.ti -1c
.RI "\fBScalePos\fP \fBscalePosition\fP () const "
.br
.ti -1c
.RI "int \fBthumbLength\fP () const "
.br
.ti -1c
.RI "int \fBthumbWidth\fP () const "
.br
.ti -1c
.RI "int \fBborderWidth\fP () const "
.br
.ti -1c
.RI "void \fBsetThumbLength\fP (int l)"
.br
.ti -1c
.RI "void \fBsetThumbWidth\fP (int w)"
.br
.ti -1c
.RI "void \fBsetBorderWidth\fP (int bw)"
.br
.ti -1c
.RI "void \fBsetMargins\fP (int x, int y)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "virtual QSize \fBminimumSizeHint\fP () const "
.br
.ti -1c
.RI "void \fBsetScaleDraw\fP (\fBQwtScaleDraw\fP *)"
.br
.ti -1c
.RI "const \fBQwtScaleDraw\fP * \fBscaleDraw\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBgetValue\fP (const QPoint &p)"
.br
.ti -1c
.RI "virtual void \fBgetScrollMode\fP (const QPoint &p, int &scrollMode, int &direction)"
.br
.ti -1c
.RI "void \fBdraw\fP (QPainter *p, const QRect &update_rect)"
.br
.ti -1c
.RI "virtual void \fBdrawSlider\fP (QPainter *p, const QRect &r)"
.br
.ti -1c
.RI "virtual void \fBdrawThumb\fP (QPainter *p, const QRect &, int pos)"
.br
.ti -1c
.RI "virtual void \fBresizeEvent\fP (QResizeEvent *e)"
.br
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *e)"
.br
.ti -1c
.RI "virtual void \fBvalueChange\fP ()"
.br
.ti -1c
.RI "virtual void \fBrangeChange\fP ()"
.br
.ti -1c
.RI "virtual void \fBscaleChange\fP ()"
.br
.ti -1c
.RI "virtual void \fBfontChange\fP (const QFont &oldFont)"
.br
.ti -1c
.RI "void \fBlayoutSlider\fP (bool update=true)"
.br
.ti -1c
.RI "int \fBxyPosition\fP (double v) const "
.br
.ti -1c
.RI "\fBQwtScaleDraw\fP * \fBscaleDraw\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQwtSlider::BGSTYLE\fP"
.PP
Background style. 
.PP
\fBSee also:\fP
.RS 4
\fBQwtSlider::QwtSlider\fP
.RE
.PP

.PP
Definition at line 62 of file qwt_slider.h.
.SS "enum \fBQwtSlider::ScalePos\fP"
.PP
Scale position. QwtSlider tries to enforce valid combinations of its orientation and scale position:
.IP "\(bu" 2
Qt::Horizonal combines with None, Top and Bottom
.IP "\(bu" 2
Qt::Vertical combines with None, Left and Right
.PP
.PP
\fBSee also:\fP
.RS 4
\fBQwtSlider::QwtSlider\fP
.RE
.PP

.PP
Definition at line 56 of file qwt_slider.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtSlider::QwtSlider (QWidget * parent, Qt::Orientation orientation = \fCQt::Horizontal\fP, \fBScalePos\fP scalePos = \fCNone\fP, \fBBGSTYLE\fP bgStyle = \fCBgTrough\fP)\fC [explicit]\fP"
.PP
Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP parent widget 
.br
\fIorientation\fP Orientation of the slider. Can be Qt::Horizontal or Qt::Vertical. Defaults to Horizontal. 
.br
\fIscalePos\fP Position of the scale. Can be QwtSlider::None, QwtSlider::Left, QwtSlider::Right, QwtSlider::Top, or QwtSlider::Bottom. Defaults to QwtSlider::None. 
.br
\fIbgStyle\fP Background style. QwtSlider::BgTrough draws the slider button in a trough, QwtSlider::BgSlot draws a slot underneath the button. An or-combination of both may also be used. The default is QwtSlider::BgTrough.
.RE
.PP
QwtSlider enforces valid combinations of its orientation and scale position. If the combination is invalid, the scale position will be set to None. Valid combinations are:
.IP "\(bu" 2
Qt::Horizonal with None, Top, or Bottom;
.IP "\(bu" 2
Qt::Vertical with None, Left, or Right.
.PP

.PP
Definition at line 65 of file qwt_slider.cpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBQwtSlider::BGSTYLE\fP QwtSlider::bgStyle () const"
.PP
\fBReturns:\fP
.RS 4
the background style.
.RE
.PP

.PP
Definition at line 735 of file qwt_slider.cpp.
.SS "int QwtSlider::borderWidth () const"
.PP
\fBReturns:\fP
.RS 4
the border width.
.RE
.PP

.PP
Definition at line 759 of file qwt_slider.cpp.
.SS "void QwtSlider::draw (QPainter * p, const QRect & update_rect)\fC [protected]\fP"
.PP
Draw the QwtSlider. 
.PP
Definition at line 517 of file qwt_slider.cpp.
.PP
References QwtAbstractScaleDraw::draw(), QwtPainter::drawFocusRect(), drawSlider(), and scaleDraw().
.PP
Referenced by paintEvent().
.SS "void QwtSlider::drawSlider (QPainter * p, const QRect & r)\fC [protected, virtual]\fP"
.PP
Draw the slider into the specified rectangle. 
.PP
Definition at line 319 of file qwt_slider.cpp.
.PP
References drawThumb(), QwtAbstractSlider::isValid(), QwtAbstractSlider::orientation(), QwtDoubleRange::value(), and xyPosition().
.PP
Referenced by draw().
.SS "void QwtSlider::drawThumb (QPainter * p, const QRect &, int pos)\fC [protected, virtual]\fP"
.PP
Draw the thumb at a position. 
.PP
Definition at line 395 of file qwt_slider.cpp.
.PP
References QwtAbstractSlider::orientation().
.PP
Referenced by drawSlider().
.SS "void QwtSlider::fontChange (const QFont & oldFont)\fC [protected, virtual]\fP"
.PP
Notify change in font. 
.PP
Definition at line 312 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::getScrollMode (const QPoint & p, int & scrollMode, int & direction)\fC [protected, virtual]\fP"
.PP
Determine scrolling mode and direction. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP point 
.br
\fIscrollMode\fP Scrolling mode 
.br
\fIdirection\fP Direction
.RE
.PP

.PP
Implements \fBQwtAbstractSlider\fP.
.PP
Definition at line 472 of file qwt_slider.cpp.
.PP
References QwtAbstractSlider::orientation(), scaleDraw(), thumbLength(), QwtDoubleRange::value(), and xyPosition().
.SS "double QwtSlider::getValue (const QPoint & p)\fC [protected, virtual]\fP"
.PP
Determine the value corresponding to a specified mouse location. 
.PP
Implements \fBQwtAbstractSlider\fP.
.PP
Definition at line 459 of file qwt_slider.cpp.
.PP
References QwtAbstractSlider::orientation().
.SS "void QwtSlider::layoutSlider (bool update_geometry = \fCtrue\fP)\fC [protected]\fP"
.PP
Recalculate the slider's geometry and layout based on the current rect and fonts. 
.PP
\fBParameters:\fP
.RS 4
\fIupdate_geometry\fP notify the layout system and call update to redraw the scale
.RE
.PP

.PP
Definition at line 546 of file qwt_slider.cpp.
.PP
References QwtScaleDraw::getBorderDistHint(), QwtScaleDraw::move(), QwtAbstractSlider::orientation(), qwtMax, scaleDraw(), and QwtScaleDraw::setLength().
.PP
Referenced by fontChange(), rangeChange(), resizeEvent(), scaleChange(), setBgStyle(), setBorderWidth(), setMargins(), setOrientation(), setScalePosition(), setThumbLength(), and setThumbWidth().
.SS "QSize QwtSlider::minimumSizeHint () const\fC [virtual]\fP"
.PP
Return a minimum size hint. 
.PP
\fBWarning:\fP
.RS 4
The return value of \fBQwtSlider::minimumSizeHint()\fP depends on the font and the scale.
.RE
.PP

.PP
Definition at line 777 of file qwt_slider.cpp.
.PP
References QwtScaleDraw::extent(), QwtScaleDraw::getBorderDistHint(), QwtScaleDraw::minLength(), QwtAbstractSlider::orientation(), qwtMax, and scaleDraw().
.PP
Referenced by sizeHint().
.SS "void QwtSlider::paintEvent (QPaintEvent * e)\fC [protected, virtual]\fP"
.PP
Qt paint event. 
.PP
Definition at line 501 of file qwt_slider.cpp.
.PP
References draw().
.SS "void QwtSlider::rangeChange ()\fC [protected, virtual]\fP"
.PP
Notify change of range. 
.PP
Reimplemented from \fBQwtDoubleRange\fP.
.PP
Definition at line 692 of file qwt_slider.cpp.
.PP
References QwtAbstractScale::autoScale(), layoutSlider(), QwtDoubleRange::maxValue(), QwtDoubleRange::minValue(), QwtDoubleRange::rangeChange(), and QwtAbstractScale::rescale().
.SS "void QwtSlider::resizeEvent (QResizeEvent * e)\fC [protected, virtual]\fP"
.PP
Qt resize event. 
.PP
Definition at line 535 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::scaleChange ()\fC [protected, virtual]\fP"
.PP
Notify changed scale. 
.PP
Reimplemented from \fBQwtAbstractScale\fP.
.PP
Definition at line 305 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "\fBQwtSlider::ScalePos\fP QwtSlider::scalePosition () const"
.PP
Return the scale position. 
.PP
Definition at line 236 of file qwt_slider.cpp.
.SS "void QwtSlider::setBgStyle (\fBBGSTYLE\fP st)"
.PP
Set the background style.
.PP
Definition at line 726 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::setBorderWidth (int bd)"
.PP
Change the slider's border width. 
.PP
\fBParameters:\fP
.RS 4
\fIbd\fP border width
.RE
.PP

.PP
Definition at line 245 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::setMargins (int xMargin, int yMargin)"
.PP
Set distances between the widget's border and internals. 
.PP
\fBParameters:\fP
.RS 4
\fIxMargin\fP Horizontal margin 
.br
\fIyMargin\fP Vertical margin
.RE
.PP

.PP
Definition at line 708 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::setOrientation (Qt::Orientation o)\fC [virtual]\fP"
.PP
Set the orientation. 
.PP
\fBParameters:\fP
.RS 4
\fIo\fP Orientation. Allowed values are Qt::Horizontal and Qt::Vertical.
.RE
.PP
If the new orientation and the old scale position are an invalid combination, the scale position will be set to None. 
.PP
\fBSee also:\fP
.RS 4
\fBQwtAbstractSlider::orientation()\fP
.RE
.PP

.PP
Reimplemented from \fBQwtAbstractSlider\fP.
.PP
Definition at line 175 of file qwt_slider.cpp.
.PP
References layoutSlider(), QwtAbstractSlider::orientation(), and QwtAbstractSlider::setOrientation().
.PP
Referenced by setScalePosition().
.SS "void QwtSlider::setScalePosition (\fBScalePos\fP s)"
.PP
Change the scale position (and slider orientation). 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP Position of the scale.
.RE
.PP
A valid combination of scale position and orientation is enforced:
.IP "\(bu" 2
if the new scale position is Left or Right, the scale orientation will become Qt::Vertical;
.IP "\(bu" 2
if the new scale position is Bottom or Top the scale orientation will become Qt::Horizontal;
.IP "\(bu" 2
if the new scale position is None, the scale orientation will not change.
.PP

.PP
Definition at line 224 of file qwt_slider.cpp.
.PP
References layoutSlider(), and setOrientation().
.SS "void QwtSlider::setThumbLength (int thumbLength)"
.PP
Set the slider's thumb length. 
.PP
\fBParameters:\fP
.RS 4
\fIthumbLength\fP new length
.RE
.PP

.PP
Definition at line 261 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "void QwtSlider::setThumbWidth (int w)"
.PP
Change the width of the thumb. 
.PP
\fBParameters:\fP
.RS 4
\fIw\fP new width
.RE
.PP

.PP
Definition at line 277 of file qwt_slider.cpp.
.PP
References layoutSlider().
.SS "QSize QwtSlider::sizeHint () const\fC [virtual]\fP"
.PP
\fBReturns:\fP
.RS 4
\fBQwtSlider::minimumSizeHint()\fP
.RE
.PP

.PP
Definition at line 767 of file qwt_slider.cpp.
.PP
References minimumSizeHint().
.SS "int QwtSlider::thumbLength () const"
.PP
\fBReturns:\fP
.RS 4
the thumb length.
.RE
.PP

.PP
Definition at line 743 of file qwt_slider.cpp.
.PP
Referenced by getScrollMode().
.SS "int QwtSlider::thumbWidth () const"
.PP
\fBReturns:\fP
.RS 4
the thumb width.
.RE
.PP

.PP
Definition at line 751 of file qwt_slider.cpp.
.SS "void QwtSlider::valueChange ()\fC [protected, virtual]\fP"
.PP
Notify change of value. 
.PP
Reimplemented from \fBQwtAbstractSlider\fP.
.PP
Definition at line 684 of file qwt_slider.cpp.
.PP
References QwtAbstractSlider::valueChange().
.SS "int QwtSlider::xyPosition (double v) const\fC [protected]\fP"
.PP
Find the x/y position for a given value v. 
.PP
Definition at line 453 of file qwt_slider.cpp.
.PP
Referenced by drawSlider(), and getScrollMode().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
