.TH "QwtSplineCurveFitter" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtSplineCurveFitter \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBQwtCurveFitter\fP.
.PP
.SH "Detailed Description"
.PP 
A curve fitter using cubic splines. 
.PP
Definition at line 62 of file qwt_curve_fitter.h.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFitMode\fP { \fBAuto\fP, \fBSpline\fP, \fBParametricSpline\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtSplineCurveFitter\fP ()"
.br
.ti -1c
.RI "virtual \fB~QwtSplineCurveFitter\fP ()"
.br
.ti -1c
.RI "void \fBsetFitMode\fP (\fBFitMode\fP)"
.br
.ti -1c
.RI "\fBFitMode\fP \fBfitMode\fP () const "
.br
.ti -1c
.RI "void \fBsetSpline\fP (const \fBQwtSpline\fP &)"
.br
.ti -1c
.RI "const \fBQwtSpline\fP & \fBspline\fP () const "
.br
.ti -1c
.RI "\fBQwtSpline\fP & \fBspline\fP ()"
.br
.ti -1c
.RI "void \fBsetSplineSize\fP (int size)"
.br
.ti -1c
.RI "int \fBsplineSize\fP () const "
.br
.ti -1c
.RI "virtual QPolygonF \fBfitCurve\fP (const QPolygonF &) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
