.TH "QwtScaleMap" 3 "17 Sep 2006" "Version 5.0.0-rc0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtScaleMap \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A scale map. 

QwtScaleMap offers transformations from a scale into a paint interval and vice versa.
.PP
Definition at line 52 of file qwt_scale_map.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtScaleMap\fP ()"
.br
.ti -1c
.RI "\fBQwtScaleMap\fP (const \fBQwtScaleMap\fP &)"
.br
.ti -1c
.RI "\fB~QwtScaleMap\fP ()"
.br
.ti -1c
.RI "\fBQwtScaleMap\fP & \fBoperator=\fP (const \fBQwtScaleMap\fP &)"
.br
.ti -1c
.RI "void \fBsetTransformation\fP (\fBQwtScaleTransformation\fP *)"
.br
.ti -1c
.RI "const \fBQwtScaleTransformation\fP * \fBtransformation\fP () const "
.br
.ti -1c
.RI "void \fBsetPaintInterval\fP (int p1, int p2)"
.br
.ti -1c
.RI "void \fBsetPaintXInterval\fP (double p1, double p2)"
.br
.ti -1c
.RI "void \fBsetScaleInterval\fP (double s1, double s2)"
.br
.ti -1c
.RI "int \fBtransform\fP (double x) const "
.br
.ti -1c
.RI "double \fBinvTransform\fP (double i) const "
.br
.ti -1c
.RI "double \fBxTransform\fP (double x) const "
.br
.ti -1c
.RI "double \fBp1\fP () const "
.br
.ti -1c
.RI "double \fBp2\fP () const "
.br
.ti -1c
.RI "double \fBs1\fP () const "
.br
.ti -1c
.RI "double \fBs2\fP () const "
.br
.ti -1c
.RI "double \fBpDist\fP () const "
.br
.ti -1c
.RI "double \fBsDist\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QT_STATIC_CONST double \fBLogMin\fP = 1.0e-150"
.br
.ti -1c
.RI "QT_STATIC_CONST double \fBLogMax\fP = 1.0e150"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtScaleMap::QwtScaleMap ()"
.PP
Constructor. 
.PP
The scale and paint device intervals are both set to [0,1].
.PP
Definition at line 84 of file qwt_scale_map.cpp.
.SS "QwtScaleMap::~QwtScaleMap ()"
.PP
Destructor
.PP
Definition at line 108 of file qwt_scale_map.cpp.
.SH "Member Function Documentation"
.PP 
.SS "double QwtScaleMap::invTransform (double i) const"
.PP
Transform an paint device value into a value in the interval of the scale. 
.PP
Definition at line 160 of file qwt_scale_map.h.
.PP
References QwtScaleTransformation::invXForm().
.PP
Referenced by QwtPainter::drawColorBar(), QwtPlotPicker::invTransform(), QwtPlotItem::invTransform(), QwtPlot::invTransform(), QwtPlotPanner::moveCanvas(), and QwtPlotSpectrogram::renderImage().
.SS "double QwtScaleMap::p1 () const"
.PP
\fBReturns:\fP
.RS 4
First border of the paint interval
.RE
.PP

.PP
Definition at line 116 of file qwt_scale_map.h.
.PP
Referenced by QwtScaleDraw::drawTick(), QwtPlotItem::paintRect(), and QwtPlotSpectrogram::renderImage().
.SS "double QwtScaleMap::p2 () const"
.PP
\fBReturns:\fP
.RS 4
Second border of the paint interval
.RE
.PP

.PP
Definition at line 124 of file qwt_scale_map.h.
.PP
Referenced by QwtScaleDraw::drawTick(), and QwtPlotSpectrogram::renderImage().
.SS "double QwtScaleMap::s1 () const"
.PP
\fBReturns:\fP
.RS 4
First border of the scale interval
.RE
.PP

.PP
Definition at line 100 of file qwt_scale_map.h.
.PP
Referenced by QwtPlotSpectrogram::renderImage(), and QwtPlotItem::scaleRect().
.SS "double QwtScaleMap::s2 () const"
.PP
\fBReturns:\fP
.RS 4
Second border of the scale interval
.RE
.PP

.PP
Definition at line 108 of file qwt_scale_map.h.
.PP
Referenced by QwtPlotSpectrogram::renderImage().
.SS "void QwtScaleMap::setPaintInterval (int p1, int p2)"
.PP
Specify the borders of the paint device interval. 
.PP
\fBParameters:\fP
.RS 4
\fIp1\fP first border 
.br
\fIp2\fP second border
.RE
.PP

.PP
Definition at line 180 of file qwt_scale_map.cpp.
.PP
References QwtScaleTransformation::type().
.PP
Referenced by QwtPlot::canvasMap(), QwtPlotRasterItem::draw(), QwtPainter::drawColorBar(), QwtScaleDraw::drawTick(), QwtRoundScaleDraw::QwtRoundScaleDraw(), QwtPlotSpectrogram::renderImage(), QwtRoundScaleDraw::setAngleRange(), and QwtPlotSvgItem::viewBox().
.SS "void QwtScaleMap::setPaintXInterval (double p1, double p2)"
.PP
Specify the borders of the paint device interval. 
.PP
\fBParameters:\fP
.RS 4
\fIp1\fP first border 
.br
\fIp2\fP second border
.RE
.PP

.PP
Definition at line 194 of file qwt_scale_map.cpp.
.PP
References QwtScaleTransformation::type().
.PP
Referenced by QwtPlot::print().
.SS "void QwtScaleMap::setScaleInterval (double s1, double s2)"
.PP
Specify the borders of the scale interval. 
.PP
\fBParameters:\fP
.RS 4
\fIs1\fP first border 
.br
\fIs2\fP second border 
.RE
.PP
\fBWarning:\fP
.RS 4
logarithmic scales might be aligned to [LogMin, LogMax]
.RE
.PP

.PP
Definition at line 153 of file qwt_scale_map.cpp.
.PP
References LogMax, LogMin, and QwtScaleTransformation::type().
.PP
Referenced by QwtPlot::canvasMap(), QwtPlot::print(), QwtPlotSpectrogram::renderImage(), setTransformation(), and QwtPlotSvgItem::viewBox().
.SS "void QwtScaleMap::setTransformation (\fBQwtScaleTransformation\fP * transformation)"
.PP
Initialize the map with a transformation
.PP
Definition at line 130 of file qwt_scale_map.cpp.
.PP
References setScaleInterval().
.PP
Referenced by QwtPlot::canvasMap(), and QwtPlot::print().
.SS "int QwtScaleMap::transform (double s) const"
.PP
Transform a point related to the scale interval into an point related to the interval of the paint device and round it to an integer. (In Qt <= 3.x paint devices are integer based. )
.PP
\fBSee also:\fP
.RS 4
\fBQwtScaleMap::xTransform\fP
.RE
.PP

.PP
Definition at line 172 of file qwt_scale_map.h.
.PP
References xTransform().
.PP
Referenced by QwtPlotCurve::closePolyline(), QwtPlotMarker::draw(), QwtPlotSpectrogram::drawContourLines(), QwtPlotCurve::drawDots(), QwtRoundScaleDraw::drawLabel(), QwtPlotCurve::drawLines(), QwtPlotCurve::drawSteps(), QwtPlotCurve::drawSticks(), QwtPlotCurve::drawSymbols(), QwtScaleDraw::drawTick(), QwtRoundScaleDraw::drawTick(), QwtRoundScaleDraw::extent(), QwtScaleDraw::labelPosition(), QwtPlotPanner::moveCanvas(), QwtPlotPicker::transform(), QwtPlotItem::transform(), and QwtPlot::transform().
.SS "const \fBQwtScaleTransformation\fP * QwtScaleMap::transformation () const"
.PP
Get the transformation. 
.PP
Definition at line 142 of file qwt_scale_map.cpp.
.PP
Referenced by QwtScaleWidget::setScaleDiv().
.SS "double QwtScaleMap::xTransform (double s) const"
.PP
Transform a point related to the scale interval into an point related to the interval of the paint device
.PP
Definition at line 143 of file qwt_scale_map.h.
.PP
References QwtScaleTransformation::type(), and QwtScaleTransformation::xForm().
.PP
Referenced by QwtPlotCurve::closestPoint(), QwtPlotCurve::drawLines(), transform(), and QwtPlotSvgItem::viewBox().

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
