QwtText
NAME
QwtText -
SYNOPSIS
Detailed Description
A class representing a text.
A QwtText is a text including a set of attributes how to render it.
Format
 A text might include control sequences (f.e tags) describing how to render it. Each format (f.e MathML, TeX, Qt Rich Text) has its own set of control sequences, that can be handles by a QwtTextEngine for this format.
Background
 A text might have a background, defined by a QPen and QBrush to improve its visibility.
Font
 A text might have an individual font.
Color
 A text might have an individual color.
Render Flags
 Flags from Qt::AlignmentFlag and Qt::TextFlag used like in QPainter::drawText.
See also:
QwtTextEngine, QwtTextLabel
Definition at line 51 of file qwt_text.h.
Public Types
enum TextFormat { AutoText = 0, PlainText, RichText, MathMLText, TeXText, OtherFormat = 100 }
enum PaintAttribute { PaintUsingTextFont = 1, PaintUsingTextColor = 2, PaintBackground = 4 }
enum LayoutAttribute { MinimumLayout = 1 }
Public Member Functions
QwtText (const QString &=QString::null, TextFormat textFormat=AutoText)
QwtText (const QwtText &)
~QwtText ()
QwtText & operator= (const QwtText &)
int operator== (const QwtText &) const
int operator!= (const QwtText &) const
void setText (const QString &, QwtText::TextFormat textFormat=AutoText)
QString text () const
bool isNull () const
bool isEmpty () const
void setFont (const QFont &)
QFont font () const
QFont usedFont (const QFont &) const
void setRenderFlags (int flags)
int renderFlags () const
void setColor (const QColor &)
QColor color () const
QColor usedColor (const QColor &) const
void setBackgroundPen (const QPen &)
QPen backgroundPen () const
void setBackgroundBrush (const QBrush &)
QBrush backgroundBrush () const
void setPaintAttribute (PaintAttribute, bool on=true)
bool testPaintAttribute (PaintAttribute) const
void setLayoutAttribute (LayoutAttribute, bool on=true)
bool testLayoutAttribute (LayoutAttribute) const
int heightForWidth (int width, const QFont &=QFont()) const
QSize textSize (const QFont &=QFont()) const
void draw (QPainter *painter, const QRect &rect) const
Protected Member Functions
const QwtTextEngine * textEngine (const QString &text, QwtText::TextFormat textFormat=AutoText) const
Member Enumeration Documentation
enum QwtText::LayoutAttribute
Layout Attributes.
The layout attributes affects some aspects of the layout of the text.
MinimumLayout
 Layout the text without its margins. This mode is useful if a text needs to be aligned accurately, like the tick labels of a scale. If QwtTextEngine::textMargins is not implemented for the format of the text, MinimumLayout has no effect.
Definition at line 129 of file qwt_text.h.
enum QwtText::PaintAttribute
Paint Attributes.
Font and color and background are optional attributes of a QwtText. The paint attributes hold the information, if they are set.
PaintUsingTextFont
 The text has an individual font.
PaintUsingTextColor
 The text has an individual color.
PaintBackground
 The text has an individual background.
Definition at line 111 of file qwt_text.h.
enum QwtText::TextFormat
Text format.
The text format defines the QwtTextEngine, that is used to render the text.
AutoText
 The text format is determined using QwtTextEngine::mightRender for all available text engines in increasing order > PlainText. If none of the text engines can render the text is rendered like PlainText.
PlainText
 Draw the text as it is, using a QwtPlainTextEngine.
RichText
 Use the Scribe framework (Qt Rich Text) to render the text.
MathMLText
 Use a MathML (http://en.wikipedia.org/wiki/MathML) render engine to display the text. A MathML text engine is not part of Qwt library and needs to be installed as plugin.
TeXText
 Use a TeX (http://en.wikipedia.org/wiki/TeX) render engine to display the text. A TeX text engine is not part of Qwt library and needs to be installed as plugin.
OtherFormat
 The number of text formats can be extended using a plugin system. Format >= OtherFormat are not used by Qwt.
See also:
QwtTextEngine
Definition at line 85 of file qwt_text.h.
Constructor & Destructor Documentation
QwtText::QwtText (const QString & text = QString::null, QwtText::TextFormat textFormat = AutoText)
Constructor
Parameters:
text Text content
textFormat Text format
Definition at line 172 of file qwt_text.cpp.
References textEngine().
QwtText::QwtText (const QwtText &)
Copy constructor.
Definition at line 182 of file qwt_text.cpp.
References d_data, and d_layoutCache.
QwtText::~QwtText ()
Destructor.
Definition at line 192 of file qwt_text.cpp.
Member Function Documentation
QBrush QwtText::backgroundBrush () const
Returns:
Background brush
See also:
setBackgroundBrush, backgroundPen
Definition at line 379 of file qwt_text.cpp.
QPen QwtText::backgroundPen () const
Returns:
Background pen
See also:
setBackgroundPen, backgroundBrush
Definition at line 358 of file qwt_text.cpp.
QColor QwtText::color () const
Return the pen color, used for painting the text.
Definition at line 322 of file qwt_text.cpp.
Referenced by QwtPlotPrintFilter::apply().
void QwtText::draw (QPainter * painter, const QRect & rect) const
Draw a text into a rectangle
Parameters:
painter Painter
rect Rectangle
Definition at line 557 of file qwt_text.cpp.
References QwtPainter::drawRect(), font(), QwtPainter::metricsMap(), QwtMetricsMap::screenToLayoutX(), and QwtMetricsMap::screenToLayoutY().
Referenced by QwtLegendItem::drawItem(), QwtScaleDraw::drawLabel(), QwtRoundScaleDraw::drawLabel(), QwtScaleWidget::drawTitle(), QwtPicker::drawTracker(), and QwtPlot::printTitle().
QFont QwtText::font () const
Return the font.
Definition at line 288 of file qwt_text.cpp.
Referenced by QwtPlotPrintFilter::apply(), draw(), heightForWidth(), and textSize().
int QwtText::heightForWidth (int width, const QFont & defaultFont = QFont()) const
Find the height for a given width
Parameters:
defaultFont Font, used for the calculation if the text has no font
width Width
Returns:
Calculated height
Definition at line 450 of file qwt_text.cpp.
References font(), QwtMetricsMap::layoutToScreenX(), QwtPainter::metricsMap(), QwtMetricsMap::screenToLayoutY(), and usedFont().
bool QwtText::isEmpty () const
Returns:
text().isEmpty()
Definition at line 152 of file qwt_text.h.
Referenced by QwtScaleDraw::drawLabel(), QwtRoundScaleDraw::drawLabel(), QwtPicker::drawTracker(), QwtRoundScaleDraw::extent(), QwtScaleDraw::labelRect(), QwtPlotLayout::minimumSizeHint(), QwtPlot::print(), and QwtPicker::trackerRect().
bool QwtText::isNull () const
Returns:
text().isNull()
Definition at line 149 of file qwt_text.h.
QwtText & QwtText::operator= (const QwtText &)
Assignement operator.
Definition at line 199 of file qwt_text.cpp.
References d_data, and d_layoutCache.
int QwtText::renderFlags () const
Returns:
Render flags
See also:
setRenderFlags
Definition at line 269 of file qwt_text.cpp.
Referenced by QwtScaleWidget::setTitle().
void QwtText::setBackgroundBrush (const QBrush & brush)
Set the background brush
Parameters:
brush Background brush
See also:
backgroundBrush, setBackgroundPen
Definition at line 369 of file qwt_text.cpp.
References setPaintAttribute().
void QwtText::setBackgroundPen (const QPen & pen)
Set the background pen
Parameters:
pen Background pen
See also:
backgroundPen, setBackgroundBrush
Definition at line 348 of file qwt_text.cpp.
References setPaintAttribute().
void QwtText::setColor (const QColor & color)
Set the pen color used for painting the text.
Parameters:
color Color
Note:
Setting the color might have no effect, when the text contains control sequences for setting colors.
Definition at line 315 of file qwt_text.cpp.
References setPaintAttribute().
Referenced by QwtPlotPrintFilter::apply(), and QwtPlotPrintFilter::reset().
void QwtText::setFont (const QFont & font)
Set the font.
Parameters:
font Font
Note:
Setting the font might have no effect, when the text contains control sequences for setting fonts.
Definition at line 281 of file qwt_text.cpp.
References setPaintAttribute().
Referenced by QwtPlotPrintFilter::apply(), and QwtPlotPrintFilter::reset().
void QwtText::setLayoutAttribute (LayoutAttribute attribute, bool on = true)
Change a layout attribute
Parameters:
attribute Layout attribute
on On/Off
See also:
testLayoutAttribute
Definition at line 421 of file qwt_text.cpp.
Referenced by QwtAbstractScaleDraw::tickLabel().
void QwtText::setPaintAttribute (PaintAttribute attribute, bool on = true)
Change a paint attribute
Parameters:
attribute Paint attribute
on On/Off
Note:
Used by setFont, setColor, setBackgroundPen and setBackgroundBrush
See also:
testPaintAttribute
Definition at line 393 of file qwt_text.cpp.
Referenced by setBackgroundBrush(), setBackgroundPen(), setColor(), and setFont().
void QwtText::setRenderFlags (int renderFlags)
Change the render flags.
The default setting is Qt::AlignCenter
Parameters:
renderFlags Bitwise OR of the flags used like in QPainter::drawText
See also:
renderFlags, QwtTextEngine::draw
Note:
Some renderFlags might have no effect, depending on the text format.
Definition at line 256 of file qwt_text.cpp.
Referenced by QwtScaleWidget::drawTitle(), QwtLegendItem::setText(), QwtScaleWidget::setTitle(), and QwtAbstractScaleDraw::tickLabel().
void QwtText::setText (const QString & text, QwtText::TextFormat textFormat = AutoText)
Assign a new text content
Parameters:
text Text content
textFormat Text format
Definition at line 229 of file qwt_text.cpp.
References textEngine().
bool QwtText::testLayoutAttribute (LayoutAttribute attribute) const
Test a layout attribute
Parameters:
attribute Layout attribute
Returns:
true, if attribute is enabled
See also:
setLayoutAttribute
Definition at line 437 of file qwt_text.cpp.
bool QwtText::testPaintAttribute (PaintAttribute attribute) const
Test a paint attribute
Parameters:
attribute Paint attribute
Returns:
true, if attribute is enabled
See also:
setPaintAttribute
Definition at line 409 of file qwt_text.cpp.
Referenced by QwtPlotPrintFilter::apply(), and QwtPlotPrintFilter::reset().
QString QwtText::text () const
Return the text.
See also:
setText
Definition at line 241 of file qwt_text.cpp.
Referenced by QwtPlot::grabProperties().
const QwtTextEngine * QwtText::textEngine (const QString & text, QwtText::TextFormat format = AutoText) const [protected]
Find the text engine for a text format
Parameters:
text Text, needed in case of AutoText
format Test format
Definition at line 626 of file qwt_text.cpp.
Referenced by QwtText(), and setText().
QSize QwtText::textSize (const QFont & defaultFont = QFont()) const
Returns the size, that is needed to render text
Parameters:
defaultFont Font of the text
Returns:
Caluclated size
Definition at line 502 of file qwt_text.cpp.
References font(), QwtMetricsMap::isIdentity(), QwtPainter::metricsMap(), QwtMetricsMap::screenToLayout(), and usedFont().
Referenced by QwtScaleDraw::drawLabel(), QwtRoundScaleDraw::drawLabel(), QwtRoundScaleDraw::extent(), QwtScaleDraw::labelRect(), QwtAbstractScaleDraw::tickLabel(), and QwtPicker::trackerRect().
QColor QwtText::usedColor (const QColor & defaultColor) const
Return the color of the text, if it has one. Otherwise return defaultColor.
Parameters:
defaultColor Default color
See also:
setColor, color, PaintAttributes
Definition at line 334 of file qwt_text.cpp.
QFont QwtText::usedFont (const QFont & defaultFont) const
Return the font of the text, if it has one. Otherwise return defaultFont.
Parameters:
defaultFont Default font
See also:
setFont, font, PaintAttributes
Definition at line 300 of file qwt_text.cpp.
Referenced by heightForWidth(), and textSize().
Author
Generated automatically by Doxygen for Qwt User's Guide from the source code.