/*
 * This C file has been generated by smidump 0.5.0.
 * It is intended to be used with the NET-SNMP agent library.
 *
 * This C file is derived from the BRIDGE-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "bridge-mib.h"

#include <ucd-snmp/asn1.h>
#include <ucd-snmp/snmp.h>
#include <ucd-snmp/snmp_api.h>
#include <ucd-snmp/snmp_impl.h>
#include <ucd-snmp/snmp_vars.h>

static oid bridge_mib_caps[] = {0,0};

void init_bridge_mib(void)
{
}

void deinit_bridge_mib()
{
    unregister_sysORTable(bridge_mib_caps, sizeof(bridge_mib_caps));
}

int term_bridge_mib()
{
    deinit_bridge_mib();
    return 0;
}

