/*
 * This C file has been generated by smidump 0.4.2-pre1.
 * It is intended to be used with the NET-SNMP agent library.
 *
 * This C file is derived from the IF-MIB module.
 *
 * $Id: if-mib-agt.c 1606 2003-12-01 12:24:15Z strauss $
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "if-mib.h"

#include <ucd-snmp/asn1.h>
#include <ucd-snmp/snmp.h>
#include <ucd-snmp/snmp_api.h>
#include <ucd-snmp/snmp_impl.h>
#include <ucd-snmp/snmp_vars.h>

static oid if_mib_caps[] = {0,0};

void init_if_mib(void)
{
}

void deinit_if_mib()
{
    unregister_sysORTable(if_mib_caps, sizeof(if_mib_caps));
}

int term_if_mib()
{
    deinit_if_mib();
    return 0;
}

